---
- name: "Send Reboot Notification"
  community.general.discord:
    webhook_id: "{{ discord_webhook_id }}"
    webhook_token: "{{ discord_webhook_token }}"
    embeds:
      - title: "✅ {{ inventory_hostname }} was rebooted ✅"
        color: 65280
        fields:
          - name: Hostname
            value: "{{ inventory_hostname }}"
          - name: IP Address
            value: "{{ ansible_host }}"
  ignore_errors: true
