---
- name: "Update Pacman Cache on {{ inventory_hostname }}"
  community.general.pacman:
    update_cache: true
  changed_when: false

- name: "Update all Pacman packages on {{ inventory_hostname }}"
  community.general.pacman:
    upgrade: true
    upgrade_extra_args: "--noconfirm --needed"
  register: pacman_results

- name: "Update all AUR packages on {{ inventory_hostname }}"
  become: true
  become_user: "{{ ansible_user }}"
  community.general.pacman:
    upgrade: true
    executable: "{{ aur_helper }}"
    upgrade_extra_args: "--noconfirm --needed"
  register: aur_results

- name: "Send Notification to Discord that {{ inventory_hostname }} was Patched"
  community.general.discord:
    webhook_id: "{{ discord_webhook_id }}"
    webhook_token: "{{ discord_webhook_token }}"
    embeds:
      - title: "👍 {{ inventory_hostname }} was patched 👍"
        color: 1127128
        fields:
          - name: Hostname
            value: "{{ inventory_hostname }}"
          - name: IP Address
            value: "{{ ansible_host }}"
  when:
    - pacman_results.changed or
      aur_results.changed
  ignore_errors: true

- name: "Send Notification to Discord that {{ inventory_hostname }} was Not Patched"
  community.general.discord:
    webhook_id: "{{ discord_webhook_id }}"
    webhook_token: "{{ discord_webhook_token }}"
    embeds:
      - title: "👍 No Patches were Required on {{ inventory_hostname }} 👍"
        color: 65280
        fields:
          - name: Hostname
            value: "{{ inventory_hostname }}"
          - name: IP Address
            value: "{{ ansible_host }}"
  when:
    - not pacman_results.changed
    - not aur_results.changed
  ignore_errors: true

- name: Check if a Reboot is Required
  ansible.builtin.command: /usr/bin/needrestart
  register: reboot_required
  changed_when: no

- name: "Reboot the {{ inventory_hostname }}"
  ansible.builtin.reboot:
    post_reboot_delay: 30
  when:
    - "'Running kernel seems to be up-to-date.' not in reboot_required.stdout"
    - "'No services need to be restarted.' not in reboot_required.stdout"
    - not inventory_hostname in groups["devices_net"]
  notify: Send Reboot Notification
