---
- name: Prelim | Include Vaulted Variables
  ansible.builtin.include_vars: vault.yml

- name: "Prelim | Verify need-restarting Command is Present on {{ inventory_hostname }}"
  ansible.builtin.dnf:
    name: dnf-utils
    state: present
  when:
    - ansible_distribution == 'Fedora' or
      ansible_distribution == 'RedHat' or
      ansible_distribution == 'AlmaLinux'

- name: "Upgrade Operating System of {{ inventory_hostname }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"

- name: Notify Discord
  ansible.builtin.include_tasks: notify_discord.yml
  become: no
