---
- name: Prelim | Include Vaulted Variables
  ansible.builtin.include_vars: vault.yml

- name: "Prelim | Verify need-restarting Command is Present on {{ inventory_hostname }}"
  ansible.builtin.dnf:
    name: dnf-utils
    state: present
  become: true
  when:
    - ansible_os_family == 'RedHat'

- name: "Prelim | Verify needrestart Command is Present on {{ inventory_hostname }}"
  community.general.pacman:
    name: needrestart
    state: present
    executable: "{{ aur_helper }}"
    extra_args: "--noconfirm --needed"
  become: true
  when:
    - ansible_os_family == 'Archlinux'

- name: "Prelim | Verify host has Docker installed"
  ansible.builtin.stat:
    path: /usr/bin/docker
  register: docker

- name: "Upgrade Operating System of {{ inventory_hostname }}"
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"
  args:
    apply:
      become: true

- name: "Upgrade Docker Compose Services of {{ inventory_hostname }}"
  ansible.builtin.include_tasks: "Docker.yml"
  args:
    apply:
      become: false
  when: docker.stat.exists and docker.stat.isreg
