---
- name: "Prelim | Include Vaulted Variables"
  ansible.builtin.include_vars: vault.yml
  no_log: true

- name: "Prelim | Verify need-restarting Command is Present"
  ansible.builtin.dnf:
    name: dnf-utils
    state: present
  become: true
  when:
    - ansible_facts['os_family'] == 'RedHat'

- name: "Prelim | Verify needrestart Command is Present"
  community.general.pacman:
    name: needrestart
    state: present
    extra_args: "--noconfirm --needed"
  become: true
  when:
    - ansible_facts['os_family'] == 'Archlinux'

- name: "Prelim | Verify host has Docker installed"
  ansible.builtin.stat:
    path: /usr/bin/docker
  register: docker

- name: "Prelim | Verify Docker daemon is responsive"
  ansible.builtin.command: docker info
  register: docker_info
  changed_when: false
  failed_when: false
  check_mode: false
  when: docker.stat.exists and docker.stat.isreg

- name: "Upgrade Operating System"
  ansible.builtin.include_tasks: "{{ ansible_facts['os_family'] }}.yml"
  args:
    apply:
      become: true

- name: "Upgrade Docker Compose Services"
  ansible.builtin.include_tasks: "Docker.yml"
  args:
    apply:
      become: true
  when:
    - docker.stat.exists and docker.stat.isreg
    - docker_info.rc is defined and docker_info.rc == 0

- name: "Perform Reboot if Required"
  ansible.builtin.include_tasks: reboot.yml
  when: perform_reboot | bool
