---
- name: Prelim | Include Vaulted Variables
  ansible.builtin.include_vars: vault.yml

- name: "Prelim | Verify need-restarting Command is Present on {{ inventory_hostname }}"
  ansible.builtin.dnf:
    name: dnf-utils
    state: present
  become: yes
  when:
    - ansible_os_family == 'RedHat'

- name: "Upgrade Operating System of {{ inventory_hostname }}"
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"
  args:
    apply:
      become: yes

- name: Notify Discord
  ansible.builtin.include_tasks: notify_discord.yml
  args:
    apply:
      become: no
