galaxy_info:
  author: Chad Zimmerman
  description: Patch OS and Docker Container Images with a single role
  company: PrymalNet

  license: MIT

  min_ansible_version: "2.10"

  platforms:
  - name: Fedora
    versions:
    - "37"
    - "38"
    - "39"
  - name: Debian
    versions:
    - "bookworm"
    - "bullseye"
  - name: ArchLinux
    versions:
      - all