---
galaxy_info:
  author: Chad Zimmerman
  description: Patch OS and Docker Container Images with a single role
  company: PrymalNet

  license: MIT

  min_ansible_version: "2.15"

  platforms:
    - name: Fedora
      versions:
        - "40"
        - "41"
        - "42"
    - name: EL
      versions:
        - "9"
    - name: Debian
      versions:
        - "bookworm"
        - "trixie"
    - name: ArchLinux
      versions:
        - all

  galaxy_tags:
    - patching
    - updates
    - security
    - docker
    - discord
    - reboot

dependencies: []
