---
discord_webhook_id: "{{ vault_discord_webhook_id }}"
discord_webhook_token: "{{ vault_discord_webhook_token }}"
compose_projects:
  - /opt/stacks/starr
  - /opt/stacks/plex
  - /opt/stacks/netboot_xyz
  - /opt/dockge
aur_helper: yay
